name: GLDG
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  rflutter_alert: ^1.0.3
  json_annotation:


dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.8.1

  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
